template: true
valuesFilePath: ./values.yml

resources:
  - name: go_app_gitrepo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: https

  - name: docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}

  - name: go_build_gitrepo
    type: GitRepo
    configuration:
      path: bhanurp/go-build
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: https
      buildOn:
        commit: true


pipelines:
  - name: go_app
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          TASK_NAME: docker_build
          TASK_VERSION: 0.0.1
          TASK_REPOSITORY: pipelines-tasks-local
          JFROG_TASK_DEBUG: "true"
          JFROG_CLI_LOG_LEVEL: debug
    steps:
      - name: test_docker_build
        type: Bash
        configuration:
          inputResources:
            - name: go_app_gitrepo
            - name: go_build_gitrepo
          outputResources:
            - name: docker_build_info
          integrations:
            - name: int_default_artifactory
        execution:
          onStart:
            - jf c show
          onExecute:
            - task: $res_go_build_gitrepo_resourcePath
              repository: pipelines-tasks-virtual
              id: go_build_task
              input:
                resourceName: go_build_gitrepo
                executionLocation: ""
                resolveRepository: go-virtual
                outputLocation: ${step_tmp_dir}
                outputFile: myapp
                rtIntegrationName: int_default_artifactory
                goCommand: ""
            - task: jfrog/docker-build@v0.0.1
              repository: pipelines-tasks-virtual
              id: docker_build_go_app
              input:
                resourceName: "go_app_gitrepo"
                dockerImage: "pipeecosys1.jfrogdev.org/pipelines-docker/go-app:latest"
            - task: jfrog/docker-push@v0.0.2
              repository: pipelines-tasks-virtual
              id: docker_push_go_app
              input:
                dockerImage: "pipeecosys1.jfrogdev.org/pipelines-docker/go-app:latest"
                autoPublishBuildInfo: "true"
                xrayScan: "true"
                failOnScan: "false"
                outputBuildInfoResourceName: "docker_build_info"
