template: true
valuesFilePath: ./values.yml

resources:
  - name: go_app_gitrepo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: https

pipelines:
  - name: go_app
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          TASK_NAME: docker_build
          TASK_VERSION: 0.0.1
          TASK_REPOSITORY: pipelines-tasks-local
    steps:
      - name: test_docker_build
        type: Bash
        configuration:
          inputResources:
            - name: go_app_gitrepo
          integrations:
            - name: int_default_artifactory
        execution:
          onExecute:
            - task: jfrog/docker-build@v0.0.1
              repository: pipelines-tasks-virtual
              id: docker_build_go_app
              input:
                resourceName: "go_app_gitrepo"
                dockerImage: "pipeecosys1.jfrogdev.org/pipelines-docker/go-app:latest"
                optionalParams: --build-arg GO_APP=/app
            - task: jfrog/docker_push@v0.0.1
              repository: pipelines-tasks-virtual
              id: docker_push_go_app
              input:
                dockerImage: "pipeecosys1.jfrogdev.org/pipelines-docker/go-app:latest"
                autoPublishBuildInfo: "true"
                xrayScan: "true"
                failOnScan: "false"