template: true
valuesFilePath: ./values.yml

resources:
  - name: go_app_gitrepo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: https

pipelines:
  - name: go_app
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u18node
            tag: "16"
            autoPull: true
      environmentVariables:
        readOnly:
          TASK_NAME: docker_build
          TASK_VERSION: 0.0.1
          TASK_REPOSITORY: pipelines-tasks-local
    steps:
      - name: test_docker_build
        type: Bash
        configuration:
          inputResources:
            - name: go_app_gitrepo
        execution:
          onExecute:
            - task: jfrog/docker_build@v0.0.1
              id: docker_build_go_app
              rtIntegration:  {{ .Values.artIntegration }}
              input:
                ResourceName: "go_app_gitrepo"
                DockerImage: "pipeecosys1.jfrogdev.org/pipelines-docker/go-app:latest"
            - task: jfrog/docker_push@v0.0.1
              id: docker_push_go_app
              rtIntegration:  {{ .Values.artIntegration }}
              input:
                DockerImage: "pipeecosys1.jfrogdev.org/pipelines-docker/go-app:latest"
                AutoPublishBuildInfo: "true"
                XrayScan: "true"
                FailOnScan: "false"